### ISSUE TITLE
Layer 4 protocol not being parsed

### ISSUE THREAD

**Issue by TonyLeeVT** [schose/TA-winfw#1]
Thanks for the great work, however the layer 4 protocol does not seem to be parsed

**Environment:**
 - TA is installed on the forwarder
 - TA is installed on the all-in-one

Using the following event as an example, UDP is not parsed.

2019-06-19 13:23:38 ALLOW **UDP** 192.168.1.38 192.168.1.250 54453 161 0 - - - - - - - SEND

**If it helps, I ended up using the following field extraction:**
^(?:[^ \n]* ){3}(?P\<transport\>\w+)

**Comment by schose** [comment]
fixed in last commit
