### ISSUE TITLE
Items to Remediate to pass Splunk Cloud vetting

### ISSUE THREAD

**Issue by knicholson0** [schose/TA-winfw#3]
Splunk Cloud operations and security teams have determined that the App you've requested is not compatible and/or secure within the Splunk Cloud service architecture. Please see their comments below:

#Custom 0.6 - TA_winfw
Review fails vetting and cannot be installed.
This is a preliminary report. More issues may be found upon further review.

Directory structure standards Ensure that the directories and files in the app adhere to hierarchy standards.

[failure] Check that when decompressed the Splunk app directory name matches the id property in the [package] stanza in app.conf. For Cloud apps, the id property must exist and match the app directory name. For on-premise apps, if the id property exists, it must match the app directory name; if there is no id property, check_for_updates must be set to False in app.conf for the check to pass.

The `app.conf` [package] stanza has an `id` property that does not match the uncompressed directory's name. `app.conf` [package] id: TA_winfw uncompressed directory name: TA-winfw-master. File: default/app.conf Line Number: 15

Once these issues are remedied you can resubmit your app for review.

If you wish to make changes to the app, you can find documentation and utilities to assist you here: http://dev.splunk.com/view/appinspect/SP-CAAAE9U

**Comment by schose** [comment]
fixed in v1.0
